title: Yeonggyun Blog
email: leeyeonggyun@gmail.com
description: 개발자' 이영균 입니다.
author: YEONG GYUN
baseurl: ''
url: 'https://blackrockdigital.github.io'

disqus: True
disqus_shortname: 'devwatsonlee'
# Social Profiles
github_username: devwatsonlee
instagram_username: gyunizero
# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

sass:
  style: compressed
# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
theme: jekyll-theme-clean-blog
