# Site
repository: devwatsonlee/devwatsonlee.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 이 영 균
title: Android Developer
email: leeyeonggyun@gmail.com
phone: 010 - 3880 - 2885
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username: devwatsonlee
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: gyunizero
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
#about_title: INTRODUCE
about_profile_image: images/leeyeonggyun.jpg
about_content: 
what


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    'Gemfile',
    'Gemfile.lock',
    'node_modules',
    'vendor/bundle/',
    'vendor/cache/',
    'vendor/gems/',
    'vendor/ruby/',
    'lib/',
    'scripts/',
    'docker-compose.yml',
  ]
